#!/usr/bin/env node

const { argv } = require("process");
const { readFileSync } = require("fs");

const package = argv[2];

const packageJson = JSON.parse(readFileSync("./package.json"));

process.exit(
    packageJson.peerDependencies && (packageJson.peerDependencies[package] || packageJson.peerDependencies["parsegraph-" + package]) ?
        0 : 1
)

