#!/usr/bin/env node
const { writeFileSync } = require("fs");
const { spawnSync } = require("child_process");
const path = require("path");

const relDir = (p)=>path.relative(__dirname, p);

const commit = (msg)=> {
  if (spawnSync("git", ["diff", "--quiet", "webpack.config.js"]).status) {
    spawnSync("git", ["commit", "webpack.config.js", "-m", msg]);
  }
}

const config = require("./webpack.config");
if (typeof config.entry === "string") {
  config.entry = {
    index:config.entry
  };
}

if (!("index" in config.entry) && path.basename(__dirname) in config.entry) {
  config.entry.index = relDir("src/index.ts");
  delete config.entry[path.basename(__dirname)];
}

if (!("demo" in config.entry)) {
  config.entry.demo = relDir("src/demo.ts");
}

writeFileSync("webpack.config.js", `const {webpackConfig, relDir} = require("./webpack.common");

module.exports = {
  entry: {
${Object.keys(config.entry).map(entry=>{
  return `    ${entry}: relDir("${relDir(config.entry[entry])}"),`
}).join("\n")}
  },
  ...webpackConfig(false),
};
`);
commit("Upgrade webpack.config.js");
