#!/bin/bash
export MICROPROJECT_DIR=$HOME/src/parsegraph/microproject
source $MICROPROJECT_DIR/init.sh

if ! test -f $DEST_DIR/package.json; then
    cp $MICROPROJECT_DIR/package.json $DEST_DIR
    sed -i "s/TODO-PACKAGE-NAME/$DIST_NAME/g" $DEST_DIR/package.json
    yarn install
    git add package.json yarn.lock
    git commit -m"Add package.json and yarn.lock"
fi

$RUN_CONFIG && $MICROPROJECT_DIR/upgrade-files
$RUN_PACKAGES && $MICROPROJECT_DIR/upgrade-packages
test -n "$BUMP_VERSION" && test "$BUMP_VERSION" != none && $MICROPROJECT_DIR/bump-version $BUMP_VERSION
