#!/usr/bin/env node
const { packageJsonHasChanges, updatePackageJson, commitPackageJson } = require("./upgradePackageJson")

if (packageJsonHasChanges()) {
  console.log("package.json has changes");
  return;
}

updatePackageJson(info=>{
  if (info.version.endsWith("-dev")) {
    info.version = info.version.slice(0, info.version.length - "-dev".length).toString();
  }
});
commitPackageJson("Remove -dev suffix from version");

updatePackageJson(info=>{
  info.main = "dist/src/index.js";
  info.types = "dist/src/index.d.ts";
});
commitPackageJson("Fix main and types to refer to index");

updatePackageJson(info=>{
  delete info.scripts;
});
commitPackageJson("Remove package.json scripts");

updatePackageJson(info=>{
    delete info.nyc;
});
commitPackageJson("Remove package.json nyc config");
