#!/bin/bash
MICROPROJECT_DIR=$HOME/src/parsegraph/microproject
DEST_DIR=`pwd`

NODE_MODULES=" \
    @babel/cli \
    @babel/core \
    @babel/plugin-proposal-class-properties \
    @babel/plugin-proposal-private-property-in-object \
    @babel/preset-env \
    @babel/preset-typescript \
    @babel/register \
    @types/chai \
    @types/mocha \
    @typescript-eslint/eslint-plugin \
    @typescript-eslint/parser \
    babel-jest \
    babel-loader \
    chai \
    eslint \
    eslint-config-google \
    eslint-config-prettier \
    express \
    glslify-loader \
    jest \
    jsdom \
    jsdom-global \
    prettier \
    raw-loader \
    source-map-loader \
    source-map-support \
    ts-loader \
    ts-mocha \
    ts-node \
    ts-shader-loader \
    typescript \
    typedoc \
    webgl-mock \
    webpack \
    webpack-cli"

OBSOLETED_MODULES=" \
    nyc \
    @istanbuljs/nyc-config-babel \
    babel-plugin-istanbul \
    babel-core \
    babel-register \
    @types/expect \
    @babel/polyfill \
    core-js \
    parsegraph-testsuite \
    @atscm/esdoc-typescript-plugin \
    mocha \
    openssl \
    esdoc \
    esdoc-standard-plugin"

yarn remove $OBSOLETED_MODULES $NODE_MODULES
yarn add $NODE_MODULES

exit

FILES="microproject.Makefile Dockerfile .babelrc .mocharc.yml tsconfig.json tsconfig.testing.json demo/demo.js tmuxify.d"
for f in $FILES; do
    if test -d $MICROPROJECT_DIR/$f; then
        mkdir -p $DEST_DIR/$f
        cp -v -r -u $MICROPROJECT_DIR/$f/* $DEST_DIR/$f
        find $DEST_DIR/$f -type f | xargs sed -i "s/TODO-PACKAGE-NAME/`basename $DEST_DIR`/g"
    elif test -f $MICROPROJECT_DIR/$f; then
        cp -v -r -u $MICROPROJECT_DIR/$f $DEST_DIR/$f
        sed -i "s/TODO-PACKAGE-NAME/`basename $DEST_DIR`/g" $f
    fi
done

DEFAULT_FILES="package-prod.json webpack.prod.js .github/workflows/prod.js.yml"
for f in $DEFAULT_FILES; do
    if ! test -f $DEST_DIR/$f; then
        mkdir -p `dirname $DEST_DIR/$f`
        cp -v -r -u $MICROPROJECT_DIR/$f $DEST_DIR/$f
        sed -i "s/TODO-PACKAGE-NAME/`basename $DEST_DIR`/g" $f
    fi
done

OBSOLETE_CONFIG=" \
    .prettierrc.json \
    package-lock.json \
    publish.sh
"
for f in $OBSOLETE_CONFIG; do
    test ! -f $f || git rm $f
done
