# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: make install-deps
    - run: make build
    - run: make tar
    - run: echo "${{ secrets.NPM_PUBLISH_TOKEN }}" >~/.npmrc
    - run: yarn publish parsegraph-TODO-PACKAGE-NAME-dev.tgz --no-git-tag-version --prepatch --preid "${{ github.run_number }}-${{ matrix.node_version }}"
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-TODO-PACKAGE-NAME-dev-${{ github.run_number }}
        path: parsegraph-TODO-PACKAGE-NAME-dev.tgz
